name: taskaway
description: "A task outsourcing platform for Malaysia"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  supabase_flutter: ^2.5.0
  formz: ^0.8.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.2
  shimmer: ^3.0.0
  markdown: ^7.2.1
  go_router: ^15.2.3
  intl: ^0.20.2
  url_launcher: ^6.2.5
  image_picker: ^1.0.8
  path: ^1.9.0
  logger: ^2.1.0
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  http: ^1.2.1
  google_fonts: ^6.2.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  uuid: ^4.3.3
  smooth_page_indicator: ^1.2.1
  shared_preferences: ^2.5.3
  web: ^1.1.1
  # Replacing url_strategy with flutter_web_plugins configuration

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  freezed: ^3.0.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.woff2
        - asset: assets/fonts/Inter-Medium.woff2
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.woff2
          weight: 600
        - asset: assets/fonts/Inter-Bold.woff2
          weight: 700
