// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjHYcqIIB5QkKwTZPOFTd1WXb1bVm7NQ0',
    appId: '1:189891927637:web:354afd0708186e52203edc',
    messagingSenderId: '189891927637',
    projectId: 'flutter-staging-taskaway',
    authDomain: 'flutter-staging-taskaway.firebaseapp.com',
    storageBucket: 'flutter-staging-taskaway.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0vKeCvlWnowfYZlDQXykmHocbXOtQFdk',
    appId: '1:189891927637:android:087a000b2e89b29d203edc',
    messagingSenderId: '189891927637',
    projectId: 'flutter-staging-taskaway',
    storageBucket: 'flutter-staging-taskaway.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpJfTvwzcKXsIXVGc33-esL5G5JnZ67BY',
    appId: '1:189891927637:ios:2934af22574b8307203edc',
    messagingSenderId: '189891927637',
    projectId: 'flutter-staging-taskaway',
    storageBucket: 'flutter-staging-taskaway.firebasestorage.app',
    iosBundleId: 'my.taskaway.taskaway',
  );
}
